In [ ]:
%load_ext sql

In [ ]:
%sql postgresql://plerin152:************@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev

'Connected: plerin152@dev'

In [ ]:
%%sql

SELECT *
FROM raw_data.user_session_channel
LIMIT 10;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(184, 'c41dd99a69df04044aa4e33ece9c9249', 'Naver'),
 (251, '0a54b19a13b6712dc04d1b49215423d8', 'Facebook'),
 (744, '05ae14d7ae387b93370d142d82220f1b', 'Facebook'),
 (265, '4c4ea5258ef3fb3fb1fc48fee9b4408c', 'Naver'),
 (45, '60131a2a3f223dc8f4753bcc5771660c', 'Youtube'),
 (262, '761efc843ff05ab74ed358713dd51c1b', 'Organic'),
 (702, '8c97dbeee3b0d40ced7f514b99a93d93', 'Instagram'),
 (113, '7f2cba89a7116c7c6b0a769572d5fad9', 'Organic'),
 (788, 'a8c6dd982010fce8701ce1aef8a2d40a', 'Google'),
 (645, '593906af0d138e69f49d251d3e7cbed0', 'Youtube')]

In [ ]:
%%sql

SELECT DISTINCT channel
FROM raw_data.user_session_channel;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[('Facebook',),
 ('Naver',),
 ('Youtube',),
 ('Instagram',),
 ('Organic',),
 ('Google',)]

In [ ]:
%%sql

SELECT channel, COUNT(1)
FROM raw_data.user_session_channel
GROUP BY 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[('Naver', 16921),
 ('Facebook', 16791),
 ('Youtube', 17091),
 ('Instagram', 16831),
 ('Organic', 16904),
 ('Google', 16982)]

In [ ]:
%%sql

SELECT *
FROM information_schema.tables
WHERE table_schema = 'raw_data';

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
8 rows affected.

[('dev', 'raw_data', 'channel', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'session_transaction', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'boolean_test', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'alert', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'vital', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'count_test', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'session_timestamp', 'BASE TABLE', None, None, None, None, None),
 ('dev', 'raw_data', 'user_session_channel', 'BASE TABLE', None, None, None, None, None)]

In [ ]:
%%sql

SELECT COUNT(1), COUNT(value), COUNT(DISTINCT value)
FROM plerin152.test_table;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(7, 6, 4)]

In [ ]:
%%sql

SELECT *
FROM plerin152.test_channel;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
4 rows affected.

[('FACEBOOK', 'test'),
 ('GOOGLE', 'test'),
 ('FACEBOOK', 'test'),
 ('GOOGLE', 'test')]

In [ ]:
%%sql

ALTER TABLE plerin152.test_channel RENAME channelname TO channel;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [ ]:
%%sql

SELECT COUNT(1)
FROM plerin152.test_channel;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(4,)]

In [ ]:
%%sql

SELECT COUNT(1)
FROM (
  SELECT DISTINCT *
  FROM plerin152.test_channel
);

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(2,)]

In [ ]:
%%sql

SELECT channel, COUNT(1)
FROM plerin152.test_channel
GROUP BY 1
ORDER BY 2 DESC;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
2 rows affected.

[('FACEBOOK', 2), ('GOOGLE', 2)]

In [ ]:
%%sql

SELECT MAX(ts), MIN(ts)
FROM raw_data.session_timestamp;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(datetime.datetime(2019, 11, 30, 23, 58, 23), datetime.datetime(2019, 5, 1, 0, 13, 11, 783000))]

In [ ]:
%%sql

SELECT TO_CHAR(ts, 'YYYY-MM'), COUNT(1)
FROM raw_data.session_timestamp
GROUP BY 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-08', 17151),
 ('2019-11', 18059),
 ('2019-05', 6261),
 ('2019-06', 10520),
 ('2019-07', 14840),
 ('2019-09', 15790),
 ('2019-10', 18899)]

In [ ]:
%%sql

SELECT TO_CHAR(ts, 'YYYY-MM') as month, COUNT(1) as count, CASE 
  WHEN COUNT(1) >= 15000 THEN '>= 15,000'
  WHEN COUNT(1) < 10000 THEN '< 10,000'
  ELSE '10,000 and 15,000'
  END 
FROM raw_data.session_timestamp
GROUP BY 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-08', 17151, '>= 15,000'),
 ('2019-11', 18059, '>= 15,000'),
 ('2019-05', 6261, '< 10,000'),
 ('2019-06', 10520, '10,000 and 15,000'),
 ('2019-07', 14840, '10,000 and 15,000'),
 ('2019-09', 15790, '>= 15,000'),
 ('2019-10', 18899, '>= 15,000')]

In [ ]:
%%sql

SELECT "group"
FROM plerin152.test;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
0 rows affected.

[]

In [ ]:
%%sql

SELECT COUNT(1)
FROM raw_data.user_session_channel
WHERE channel not like '%oo%';

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(67747,)]

In [ ]:
%%sql

SELECT COUNT(1)
FROM raw_data.session_timestamp
WHERE ts BETWEEN '2019-05-01' AND '2019-05-05'

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(600,)]

In [ ]:
%%sql

SELECT COUNT(1)
FROM plerin152.test_table
WHERE value is NULL;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(1,)]

In [ ]:
%%sql

SELECT COUNT(NULL), 1/NULL, 1+NULL;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(0, None, None)]

In [ ]:
%%sql

SELECT value
FROM plerin152.test_table;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(None,), (1,), (1,), (0,), (0,), (4,), (3,)]

In [ ]:
%%sql

SELECT value, 100/NULLIF(value, 0)
FROM plerin152.test_table
ORDER BY 2 ASC;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(4, 25), (3, 33), (1, 100), (1, 100), (None, None), (0, None), (0, None)]

In [ ]:
%%sql

SELECT value, COALESCE(value, 1)
FROM plerin152.test_table;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[(None, 1), (1, 1), (1, 1), (0, 0), (0, 0), (4, 4), (3, 3)]

In [ ]:
%%sql

SELECT EXTRACT(HOUR FROM ts), COUNT(1) as session_cnt
FROM raw_data.session_timestamp
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[(15, 15339)]

In [ ]:
%%sql

SELECT 
  channel,
  COUNT(1) AS session_cnt,
  COUNT(DISTINCT userId) AS user_cnt
FROM raw_data.user_session_channel
GROUP BY 1
ORDER BY 2;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[('Facebook', 16791, 889),
 ('Instagram', 16831, 895),
 ('Organic', 16904, 895),
 ('Naver', 16921, 882),
 ('Google', 16982, 893),
 ('Youtube', 17091, 889)]

In [ ]:
%%sql

SELECT 
  channel,
  COUNT(1) AS session_cnt
FROM raw_data.user_session_channel
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
1 rows affected.

[('Youtube', 17091)]

In [ ]:
%%sql

SELECT *
FROM raw_data.session_timestamp
LIMIT 10;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[('7cdace91c487558e27ce54df7cdb299c', datetime.datetime(2019, 5, 1, 0, 13, 11, 783000)),
 ('7ed2d3454c5eea71148b11d0c25104ff', datetime.datetime(2019, 5, 1, 10, 18, 43, 210000)),
 ('fd0efcca272f704a760c3b61dcc70fd0', datetime.datetime(2019, 5, 1, 13, 45, 19, 793000)),
 ('c5f441cd5f43eb2f2c024e1f8b5d00cd', datetime.datetime(2019, 5, 1, 15, 3, 54, 650000)),
 ('3d191ef6e236bd1b9bdb9ff4743c47fe', datetime.datetime(2019, 5, 1, 15, 33, 58, 197000)),
 ('cd0b43eac0392accf3624b7372dec36e', datetime.datetime(2019, 5, 1, 16, 33, 3, 463000)),
 ('c67ba7c4c5c0cd4cc3e3a7146fe5c015', datetime.datetime(2019, 5, 1, 17, 42, 13, 580000)),
 ('63dfdeb1ff9ff09ecc3f05d2d7221ffa', datetime.datetime(2019, 5, 1, 18, 35, 48, 620000)),
 ('8d3215ae97598264ad6529613774a038', datetime.datetime(2019, 5, 1, 21, 21, 12, 953000)),
 ('4c4c937b67cc8d785cea1e42ccea185c', datetime.datetime(2019, 5, 1, 23, 50, 38))]

In [ ]:
%%sql

SELECT *
FROM raw_data.user_session_channel
LIMIT 10;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
10 rows affected.

[(184, 'c41dd99a69df04044aa4e33ece9c9249', 'Naver'),
 (251, '0a54b19a13b6712dc04d1b49215423d8', 'Facebook'),
 (744, '05ae14d7ae387b93370d142d82220f1b', 'Facebook'),
 (265, '4c4ea5258ef3fb3fb1fc48fee9b4408c', 'Naver'),
 (45, '60131a2a3f223dc8f4753bcc5771660c', 'Youtube'),
 (262, '761efc843ff05ab74ed358713dd51c1b', 'Organic'),
 (702, '8c97dbeee3b0d40ced7f514b99a93d93', 'Instagram'),
 (113, '7f2cba89a7116c7c6b0a769572d5fad9', 'Organic'),
 (788, 'a8c6dd982010fce8701ce1aef8a2d40a', 'Google'),
 (645, '593906af0d138e69f49d251d3e7cbed0', 'Youtube')]

In [ ]:
%%sql

SELECT 
  TO_CHAR(st.ts, 'YYYY-MM') as month, 
  usc.channel,
  COUNT(DISTINCT usc.userid) as cnt
FROM
  raw_data.session_timestamp st
  JOIN raw_data.user_session_channel usc ON st.sessionid = usc.sessionid
GROUP BY 1, 2
ORDER BY 1 DESC, 2

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
42 rows affected.

[('2019-11', 'Facebook', 688),
 ('2019-11', 'Google', 688),
 ('2019-11', 'Instagram', 669),
 ('2019-11', 'Naver', 667),
 ('2019-11', 'Organic', 677),
 ('2019-11', 'Youtube', 677),
 ('2019-10', 'Facebook', 698),
 ('2019-10', 'Google', 699),
 ('2019-10', 'Instagram', 707),
 ('2019-10', 'Naver', 713),
 ('2019-10', 'Organic', 709),
 ('2019-10', 'Youtube', 705),
 ('2019-09', 'Facebook', 597),
 ('2019-09', 'Google', 599),
 ('2019-09', 'Instagram', 588),
 ('2019-09', 'Naver', 592),
 ('2019-09', 'Organic', 592),
 ('2019-09', 'Youtube', 588),
 ('2019-08', 'Facebook', 611),
 ('2019-08', 'Google', 610),
 ('2019-08', 'Instagram', 621),
 ('2019-08', 'Naver', 626),
 ('2019-08', 'Organic', 608),
 ('2019-08', 'Youtube', 614),
 ('2019-07', 'Facebook', 558),
 ('2019-07', 'Google', 556),
 ('2019-07', 'Instagram', 567),
 ('2019-07', 'Naver', 553),
 ('2019-07', 'Organic', 557),
 ('2019-07', 'Youtube', 564),
 ('2019-06', 'Facebook', 414),
 ('2019-06', 'Google', 412),
 ('2019-06', 'Instagram', 410),
 ('2019-06', 'Naver', 398),
 ('2019-06', 'Organic', 416),
 ('2019-06', 'Youtube', 400),
 ('2019-05', 'Facebook', 247),
 ('2019-05', 'Google', 253),
 ('2019-05', 'Instagram', 234),
 ('2019-05', 'Naver', 237),
 ('2019-05', 'Organic', 238),
 ('2019-05', 'Youtube', 244)]

In [ ]:
%%sql

CREATE TABLE plerin152.monthly_active_user_summary AS
(
  SELECT TO_CHAR(ts, 'YYYY-MM') AS month, COUNT(DISTINCT userid)
  FROM raw_data.user_session_channel A
  JOIN raw_data.session_timestamp B ON A.sessionid = B.sessionid
  GROUP BY 1
  ORDER BY 1 DESC
);

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.

[]

In [ ]:
%%sql

SELECT *
FROM plerin152.monthly_active_user_summary;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
7 rows affected.

[('2019-10', 763),
 ('2019-09', 639),
 ('2019-07', 623),
 ('2019-06', 459),
 ('2019-05', 281),
 ('2019-11', 721),
 ('2019-08', 662)]

In [ ]:
%%sql

SELECT 'kim', 'kihoon'

UNION

SELECT 'john', 'kim'

UNION

SELECT 'lenovo', 'thinkpad'

ORDER BY 1;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
3 rows affected.

[('john', 'kim'), ('kim', 'kihoon'), ('lenovo', 'thinkpad')]

In [ ]:
%%sql

DROP TABLE IF EXISTS plerin152.vital;
CREATE TABLE plerin152.vital (
    UserID int,
    VitalID	int,
    Date date,
    Weight int
);
INSERT INTO plerin152.vital VALUES
(100,	1, '2020-01-01', 75),
(100, 3, '2020-01-02', 78),
(101, 2, '2020-01-01', 90),
(101, 4, '2020-01-02', 95);

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.
4 rows affected.

[]

In [ ]:
%%sql

DROP TABLE IF EXISTS plerin152.alert;
CREATE TABLE plerin152.alert (
    AlertID int,
    VitalID	int,
    AlertType varchar(32),
    Date date,
    UserID int
);
INSERT INTO plerin152.alert VALUES
 (1,	4, 'WeightIncrease', '2020-01-01', 101),
 (2, NULL, 'MissingVital', '2020-01-04', 100),
 (3, NULL, 'MissingVital', '2020-01-04', 101);

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
Done.
Done.
3 rows affected.

[]

In [ ]:
%%sql

SELECT * FROM plerin152.Vital v
FULL JOIN plerin152.Alert a ON v.vitalID = a.vitalID;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
6 rows affected.

[(101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (None, None, None, None, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (None, None, None, None, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, None, None, None, None, None),
 (100, 1, datetime.date(2020, 1, 1), 75, None, None, None, None, None),
 (100, 3, datetime.date(2020, 1, 2), 78, None, None, None, None, None)]

In [ ]:
%%sql

SELECT * FROM plerin152.Vital v
CROSS JOIN plerin152.Alert a;

 * postgresql://plerin152:***@learnde.cduaw970ssvt.ap-northeast-2.redshift.amazonaws.com:5439/dev
12 rows affected.

[(100, 1, datetime.date(2020, 1, 1), 75, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (100, 3, datetime.date(2020, 1, 2), 78, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (101, 4, datetime.date(2020, 1, 2), 95, 1, 4, 'WeightIncrease', datetime.date(2020, 1, 1), 101),
 (100, 1, datetime.date(2020, 1, 1), 75, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (100, 3, datetime.date(2020, 1, 2), 78, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (101, 2, datetime.date(2020, 1, 1), 90, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (101, 4, datetime.date(2020, 1, 2), 95, 2, None, 'MissingVital', datetime.date(2020, 1, 4), 100),
 (100, 1, datetime.date(2020, 1, 1), 75, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (100, 3, datetime.date(2020, 1, 2), 78, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 2, datetime.date(2020, 1, 1), 90, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101),
 (101, 4, datetime.date(2020, 1, 2), 95, 3, None, 'MissingVital', datetime.date(2020, 1, 4), 101)]